# Import the helper functions

In [1]:
from datetime import datetime
from libs.utils.onspot_oneoff import (
    load_local_settings,
    pull_by_esqids,
    pull_by_address_file,
    get_results_frame,
)

_ = load_local_settings("local.settings.json")

# Pull by esquids

In [ ]:
id_list = ["EF~35658"]

In [ ]:
result = pull_by_esqids(
    esqids=id_list,
    start=datetime(2026, 1, 1),
    end=datetime(2026, 2, 1),
    pull_type="devices",
    wait=True,
    timeout_seconds=900,
    verbose=True
)
df = get_results_frame(result)
df.head()

{'type': 'FeatureCollection', 'features': [{'id': 'WWMIcyESiXlnPuhwOD9tUyc0t50zzzpJ', 'type': 'Feature', 'geometry': {'type': 'Polygon', 'coordinates': [[[-84.17577403660988, 33.48964977022395], [-84.17597404003406, 33.48952548781261], [-84.175907372226, 33.48946661713404], [-84.17571325125535, 33.48958108786071], [-84.17577403660988, 33.48964977022395]]]}, 'properties': {'name': 'cmjdc2uuc001i7tp5slpijfo5', 'start': '2026-01-01T00:00:00', 'end': '2026-02-01T00:00:00', 'hash': False, 'callback': 'https://webhook.site/.../da570918d0b14f419fb5e66897d2ebfe', 'outputLocation': 'az://esquireonspot.blob.core.windows.net/dashboard/oneoff/042fde71dd6a4f22beb4c7910c85adff/devices?se=2026-04-17T15%3A13%3A57Z&sp=rwl&sv=2023-11-03&sr=c&sig=NeMhwnpmLNx5i7mNLBHkGhmgXII7EHQzt7QaQ7gSZ/A%3D'}}]}
Polling devices results for ESQID pull...
  prefix: oneoff/042fde71dd6a4f22beb4c7910c85adff/devices
  found:  0 / 1
  found:  0 / 1
  found:  1 / 1
Completed.

,deviceid,source_blob
0,70ae586e-3e8c-4c76-b412-e9e14f6cc9ae,oneoff/042fde71dd6a4f22beb4c7910c85adff/device...
1,0c4a5df5-3ec5-4c6d-9fe4-2f56a6907926,oneoff/042fde71dd6a4f22beb4c7910c85adff/device...
2,7816867b-85cb-4926-8431-cf73ce6d0d88,oneoff/042fde71dd6a4f22beb4c7910c85adff/device...
3,0bbc52aa-b26e-431d-b18b-b52edb465fd2,oneoff/042fde71dd6a4f22beb4c7910c85adff/device...
4,bc27a347-7749-45b8-84a4-8ae3c0fc9817,oneoff/042fde71dd6a4f22beb4c7910c85adff/device...

# Pull by addresses

Requires a csv with the field names 
* address
* city
* state
* zipCode	
* plus4Code

In [2]:
file_path = "C:/Users/Owner/Downloads/addresses_onspot_test.csv"

In [3]:
result = pull_by_address_file(
    local_path=file_path,
    pull_type="devices",
    wait=True,
    timeout_seconds=900,
    verbose=True
)
df = get_results_frame(result)
df.head()

{'hash': False, 'name': '3551b75fd1a54e6885bf9735acc20cf2', 'fileName': '658851f5029d41d08abffd138d3bf915.csv', 'fileFormat': {'delimiter': ',', 'quoteEncapsulate': True}, 'mappings': {'street': ['address'], 'city': ['city'], 'state': ['state'], 'zip': ['zipCode'], 'zip4': ['plus4Code']}, 'matchAcceptanceThreshold': 29.9, 'sources': ['az://esquireonspot.blob.core.windows.net/dashboard/oneoff/c4d85728ccb548a1b3126aff272fcea2/inputs/addresses_onspot_test.csv?se=2026-04-17T15%3A29%3A10Z&sp=r&sv=2023-11-03&sr=b&sig=cFGfjFyKDIimXialMZshkg20cRdjL1hFYskxrZiOKcE%3D'], 'outputLocation': 'az://esquireonspot.blob.core.windows.net/dashboard/oneoff/c4d85728ccb548a1b3126aff272fcea2/devices?se=2026-04-17T15%3A29%3A10Z&sp=rwl&sv=2023-11-03&sr=c&sig=2UG9XKIT1rW324Vk661B2yaERe35C0RsvIXY86Klehg%3D', 'callback': 'https://webhook.site/...'}
Polling devices results for address pull...
  prefix: oneoff/c4d85728ccb548a1b3126aff272fcea2/devices
  found:  0 / 1
  found:  0 / 1
  found:  1 / 1
Completed.

,deviceid,source_blob
0,9b83b202-3cc5-4bcd-9adc-f476f88a25b9,oneoff/c4d85728ccb548a1b3126aff272fcea2/device...
1,70b41932-e9cb-4372-8aa4-9594784a9b75,oneoff/c4d85728ccb548a1b3126aff272fcea2/device...
2,77495f24-fefa-40af-8800-7c60d094027e,oneoff/c4d85728ccb548a1b3126aff272fcea2/device...
3,97eae5eb-52b3-4ba8-9c09-46494355b1be,oneoff/c4d85728ccb548a1b3126aff272fcea2/device...
4,32b63116-30e2-4563-ba1b-bc1f21357a13,oneoff/c4d85728ccb548a1b3126aff272fcea2/device...

# Write output

In [ ]:
output_path = "C:/Users/Owner/Downloads/maids.csv"

df[['deviceid']].to_csv(
    output_path, 
    index=False
    )